import java.awt.CardLayout;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author X1 Carbon
 */
public class FrameDasboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameDasboard.class.getName());
    private CardLayout  CardLayout; 

    /**
     * Creates new form FrameDasboard
     */
    public FrameDasboard() {
        initComponents();
        inisiasiPanel();
    }
    void inisiasiPanel(){
         CardLayout = (CardLayout)panelContent.getLayout();
         panelContent.add(new panelDasboard(), "dasboard");
         panelContent.add(new panelJurusan(), "jurusan");
         panelContent.add(new panelGuru(), "guru");
         panelContent.add(new panelKelas(), "kelas");
         panelContent.add(new panelSiswa(), "siswa");
         panelContent.add(new panelAbout(), "about");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bDasboard = new javax.swing.JButton();
        bJurusan = new javax.swing.JButton();
        bKelas = new javax.swing.JButton();
        bSiswa = new javax.swing.JButton();
        bGuru = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Alumni");
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setPreferredSize(new java.awt.Dimension(1024, 600));

        panelSidebar.setBackground(new java.awt.Color(0, 153, 255));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 604));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BiMortarboardFill.png"))); // NOI18N
        jLabel1.setText("Aloomni");

        bDasboard.setBackground(new java.awt.Color(51, 153, 255));
        bDasboard.setForeground(new java.awt.Color(255, 255, 255));
        bDasboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-dashboard-20 (1).png"))); // NOI18N
        bDasboard.setText("Dashboard");
        bDasboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDasboard.addActionListener(this::bDasboardActionPerformed);

        bJurusan.setBackground(new java.awt.Color(51, 153, 255));
        bJurusan.setForeground(new java.awt.Color(255, 255, 255));
        bJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-department-20.png"))); // NOI18N
        bJurusan.setText("Jurusan ");
        bJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJurusan.addActionListener(this::bJurusanActionPerformed);

        bKelas.setBackground(new java.awt.Color(51, 153, 255));
        bKelas.setForeground(new java.awt.Color(255, 255, 255));
        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-class-20.png"))); // NOI18N
        bKelas.setText("Kelas");
        bKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKelas.addActionListener(this::bKelasActionPerformed);

        bSiswa.setBackground(new java.awt.Color(51, 153, 255));
        bSiswa.setForeground(new java.awt.Color(255, 255, 255));
        bSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-20.png"))); // NOI18N
        bSiswa.setText("Siswa");
        bSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSiswa.addActionListener(this::bSiswaActionPerformed);

        bGuru.setBackground(new java.awt.Color(51, 153, 255));
        bGuru.setForeground(new java.awt.Color(255, 255, 255));
        bGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-teacher-20.png"))); // NOI18N
        bGuru.setText("Guru");
        bGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGuru.addActionListener(this::bGuruActionPerformed);

        bAbout.setBackground(new java.awt.Color(51, 153, 255));
        bAbout.setForeground(new java.awt.Color(255, 255, 255));
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-about-20.png"))); // NOI18N
        bAbout.setText("About");
        bAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAbout.addActionListener(this::bAboutActionPerformed);

        bLogout.setBackground(new java.awt.Color(51, 153, 255));
        bLogout.setForeground(new java.awt.Color(255, 255, 255));
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-20.png"))); // NOI18N
        bLogout.setText("Logout");
        bLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLogout.addActionListener(this::bLogoutActionPerformed);

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addComponent(bDasboard, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bDasboard)
                .addGap(0, 0, 0)
                .addComponent(bJurusan)
                .addGap(0, 0, 0)
                .addComponent(bGuru)
                .addGap(0, 0, 0)
                .addComponent(bKelas)
                .addGap(0, 0, 0)
                .addComponent(bSiswa)
                .addGap(0, 0, 0)
                .addComponent(bAbout)
                .addGap(0, 0, 0)
                .addComponent(bLogout)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDasboardActionPerformed
        // TODO add your handling code here:
        CardLayout.show(panelContent,"dasboard");
    }//GEN-LAST:event_bDasboardActionPerformed

    private void bJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJurusanActionPerformed
        // TODO add your handling code here:
        CardLayout.show(panelContent,"jurusan");
    }//GEN-LAST:event_bJurusanActionPerformed

    private void bKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKelasActionPerformed
        // TODO add your handling code here:
        CardLayout.show(panelContent,"kelas");
    }//GEN-LAST:event_bKelasActionPerformed

    private void bSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiswaActionPerformed
        // TODO add your handling code here:
        CardLayout.show(panelContent,"siswa");
    }//GEN-LAST:event_bSiswaActionPerformed

    private void bGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuruActionPerformed
           // TODO add your handling code here:
        CardLayout.show(panelContent,"guru");
    }//GEN-LAST:event_bGuruActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
        CardLayout.show(panelContent,"about");
    }//GEN-LAST:event_bAboutActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(
        null,
        "Apakah Anda yakin ingin keluar?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION);
        
        switch (pilihan){
            case JOptionPane.YES_OPTION:
            dispose();
            new FrameLogin().setVisible(true);
            break;
            case JOptionPane.NO_OPTION:
            dispose();
            new FrameLogin().setVisible(true);
            break;
            default:
            break;
                
            
        }
    }//GEN-LAST:event_bLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.put("Button.borderWidth" , 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameDasboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDasboard;
    private javax.swing.JButton bGuru;
    private javax.swing.JButton bJurusan;
    private javax.swing.JButton bKelas;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
